### PR TITLE
Created Mission Page

### PR DESCRIPTION
**Pull request by Dhanvi-IBM**
@95

### CODE REVIEW

**Comment by Sahaj-IBM** [comment]
#89 #94

**Comment by SamLee-IBM** [comment]
Can you make the text more contained to the left side, currently the text bleeds all the way to the left edge and it looks a little disorganized

**Comment by Dhanvi-IBM** [comment]
Just fixed the text bleeding

**Review by SamLee-IBM — APPROVED** [review]

**Comment by Sahaj-IBM** [comment]
Lets try to use the Grid Format like we do on the other pages. Using the right grids, columns, rows, and classnames will ensure consistency in UI

Screenshot 2024-08-01 at 4 43 38 PM

**Review by SamLee-IBM — APPROVED** [review]

**Pull request merged**
